### ISSUE TITLE
Planned episodes, dates and sponsorships (Evergreen Issue, never closes)

### ISSUE THREAD

**Issue by lefticus** [lefticus/cpp_weekly#336]
- [ ] 400 - 2023-10-30 - "C++ is 40... Is C++ Dying?" #193  (JetBrains)
- [ ] 401 - 2023-11-06 - "C++23's views::chunk and views::stride" #296 (Undo)
- [ ] 402 - 2023-11-13 - "Reviewing My 25 Year Old C++ Code! (From University)" (JetBrains)
- [ ] 403 - 2023-11-20 - "Easy Coroutines with CppCoro" #78 
- [ ] 404 - 2023-11-27 - (JetBrains)
- [ ] 405 - 2023-12-04 - "Dogbolt Decompiler Explorer" #120 (Undo)
- [ ] 406 - 2023-12-11 - (JetBrains)
- [ ] 407 - 2023-12-18 - "What is Padding and Why Should You Care?" #173 
- [ ] 408 - 2023-12-25 - (JetBrains)
- [ ] 409 - 2024-01-01 - 
- [ ] 410 - 2024-01-08 - (JetBrains)
- [ ] 411 - 2024-01-15 - "Intro to Exceptions" #315 (Undo)
- [ ] 412 - 2024-01-22 - (JetBrains)
- [ ] 413 - 2024-01-29 - 
- [ ] 414 - 2024-02-05 - (JetBrains)
- [ ] 415 - 2024-02-12 - 
- [ ] 416 - 2024-02-19 - (JetBrains)
- [ ] 417 - 2024-02-26 - 
- [ ] 418 - 2024-03-04 - (JetBrains)
- [ ] 419 - 2024-03-11 -

**Comment by fcolecumberri** [comment]
from `514` the year should be `2026` or you might need a time machine.

**Comment by lefticus** [comment]
> from `514` the year should be `2026` or you might need a time machine.

It happens :D

**Comment by lefticus** [comment]
2026 from here:

- [x] 514 - 2026-01-05 - #508
- [x] 515 - 2026-01-12 - #473 (HRT) (Recorded)
- [x] 516 - 2026-01-19 - #415 (JB) (Recorded)
- [x] 517 - 2026-01-26 - #133 (HRT) (Recorded)
- [x] 518 - 2026-02-02 - #513 (JB) (Recorded)
- [x] 519 - 2026-02-09 - #487 (Recorded)
- [x] 520 - 2026-02-16 - #521 (JB) (Recorded)
- [x] 521 - 2026-02-23 - CppCast 404 (Recorded)
- [x] 522 - 2026-03-02 - #471 (JB) (Recorded)
- [x] 523 - 2026-03-09 - #506 (Recorded)
- [x] 524 - 2026-03-16 - #516 (JB) (Recorded)
- [x] 525 - 2026-03-23 - CppCast 405
- [x] 526 - 2026-03-30 - #514 (JB) (Recorded)
- [x] 527 - 2026-04-06 - #522 (Recorded)
- [x] 528 - 2026-04-13 - #161 (JB)  (Recorded
- [x] 529 - 2026-04-20 - CppCast 406 (Recorded)
- [x] 530 - 2026-04-27 - #523  (JB) (Recorded)
- [x] 531 - 2026-05-04 - #541 (Recorded)
- [x] 532 - 2026-05-11 - #101 (JB) (Recorded)
- [x] 533 - 2026-05-18 - CppCast 407
- [x] 534 - 2026-05-25 - #18 (JB) (Recorded)
- [x] 535 - 2026-06-01 - #542 (Recorded)
- [x] 536 - 2026-06-08 - #200 (HRT) (Recorded)
- [x] 537 - 2026-06-15 - CppCast 408
- [x] 538 - 2026-06-22 - #496 (HRT) (Recorded)
- [x] 539 - 2026-06-29 - #543 (Recorded)
- [x] 540 - 2026-07-06 - #517 (HRT) (Recorded)
- [x] 541 - 2026-07-13 - CppCast 409
- [x] 542 - 2026-07-20 - #392 (HRT) (Recorded)
- [x] 543 - 2026-07-27 - #507 (Recorded)
- [x] 544 - 2026-08-03 - #380 (HRT) (Recorded)
- [x] 545 - 2026-08-10 - CppCast 410
- [x] 546 - 2026-08-17 - #512 (HRT) (Recorded)
- [x] 547 - 2026-08-24 - #553 (Recorded)
- [x] 548 - 2025-08-31 - #554 (Recorded)
- [x] 549 - 2026-09-07 - CppCast 411
- [x] 550 - 2026-09-14 - #552 (NDC) (Recorded)
- [x] 551 - 2026-09-21 - #484 (Recorded)
- [x] 552 - 2026-09-28 - #477 (Recorded)
- [ ] 553 - 2026-10-05 - CppCast 412
- [ ] 554 - 2026-10-12 - #524 (Recorded)
- [ ] 556 - 2026-10-19 - #312 
- [ ] 557 - 2026-10-26 - #509
- [ ] 558 - 2026-11-02 - CppCast 413
- [ ] 559 - 2026-11-09 - #474
- [ ] 560 - 2026-11-16 - #531 (Recorded)
- [ ] 561 - 2026-11-23 - #442 (Recorded)

Episode 0 (recorded)
